version: "3.8"
services:
  tor:
    image: dperson/torproxy
    command: "-p 9050"   
    ports:
      - "9050:9050"
  
  app:
    build: .
    ports:
      - "8080:8080"       
    environment:
      HTTP_PROXY: "socks5h://tor:9050"
      HTTPS_PROXY: "socks5h://tor:9050"
    depends_on:
      - tor

